from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

DEFAULT_TARGETS = (
    "apps/web/app/layout.tsx",
    "apps/web/app/operator-console.tsx",
)

BANNED_PHRASES: tuple[tuple[str, str], ...] = (
    ("production-ready code", "Do not claim generated code is production-ready without credentialed/live proof."),
    ("re-run CI automatically", "CI evidence analysis is recorded and human-gated; do not imply automatic CI reruns."),
    ("planned, tested, security-scanned draft pull requests", "Use gated records/evidence wording instead of end-to-end PR claims."),
    ("Agentic GitHub Development", "Use issue-planning/control-plane wording for public hero surfaces."),
    ("safe draft pull requests", "Use reviewed plans and gated draft PR workflow wording."),
    ("agentic GitHub development command center", "Use issue planning/review/readiness console wording."),
    ("Draft PRs created", "Use draft PR records when real GitHub writes may be disabled."),
    ("Track issues from triage to draft pull request", "Avoid implying every issue reaches a live PR."),
    ("Production ready", "Use readiness checks passed unless release evidence is complete."),
    ("CI Failure Debugger", "Use CI evidence analyzer; fix generation is not autonomous."),
    ("Ask Agent to Propose Fix", "Use analyze supplied CI evidence or revision-plan wording."),
    ("generated by RepoPilot", "Use tracked PR record/evidence wording unless live generation is proven."),
    ("Verified catalog", "Use backend catalog; catalog presence does not prove provider privacy."),
    ("Model provider responded successfully", "Make live provider verification explicit."),
    ("Model provider saved securely", "State write-only encrypted local storage semantics."),
    ("Calls the provider models endpoint", "State that verification is a live provider request with no repository source."),
)

REQUIRED_PHRASES: tuple[tuple[str, str], ...] = (
    ("Local-first GitHub issue planning", "Public metadata should preserve local-first positioning."),
    ("External data transfer", "Model settings must warn about provider data transfer."),
    ("source-transfer consent", "Embedding/source transfer opt-in must be visible."),
    ("Verify with live call", "Provider verification button must disclose live outbound call."),
    ("CI Evidence Analyzer", "CI screen must avoid autonomous-fix wording."),
    ("Draft PR records", "Dashboard/PR surfaces must distinguish local records from live PR writes."),
)


@dataclass(frozen=True)
class TruthFinding:
    check: str
    path: str
    line: int
    phrase: str
    detail: str


@dataclass(frozen=True)
class TruthGuardReport:
    target_count: int
    findings: list[TruthFinding]

    @property
    def failed(self) -> bool:
        return bool(self.findings)

    def as_dict(self) -> dict[str, object]:
        return {
            "target_count": self.target_count,
            "failed": self.failed,
            "findings": [asdict(finding) for finding in self.findings],
        }


def _line_number(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def _relative(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def scan_targets(root: Path, targets: tuple[str, ...] = DEFAULT_TARGETS) -> TruthGuardReport:
    findings: list[TruthFinding] = []
    target_paths = [root / target for target in targets]
    readable_targets = [path for path in target_paths if path.exists()]
    combined_text = ""

    for path in readable_targets:
        text = path.read_text(encoding="utf-8")
        combined_text += f"\n{text}"
        lower_text = text.lower()
        for phrase, detail in BANNED_PHRASES:
            start = 0
            phrase_lower = phrase.lower()
            while True:
                index = lower_text.find(phrase_lower, start)
                if index == -1:
                    break
                findings.append(
                    TruthFinding(
                        check="banned_phrase",
                        path=_relative(path, root),
                        line=_line_number(text, index),
                        phrase=phrase,
                        detail=detail,
                    )
                )
                start = index + len(phrase_lower)

    combined_lower = combined_text.lower()
    for phrase, detail in REQUIRED_PHRASES:
        if phrase.lower() not in combined_lower:
            findings.append(
                TruthFinding(
                    check="required_phrase",
                    path=",".join(targets),
                    line=0,
                    phrase=phrase,
                    detail=detail,
                )
            )

    return TruthGuardReport(target_count=len(readable_targets), findings=findings)


def render_markdown(report: TruthGuardReport) -> str:
    lines = [
        "# RepoPilot UI Truth Guard",
        "",
        f"- Targets scanned: `{report.target_count}`",
        f"- Status: `{'failed' if report.failed else 'passed'}`",
        "",
    ]
    if not report.findings:
        lines.append("No banned overclaim phrases or missing required privacy labels were found.")
        return "\n".join(lines) + "\n"

    lines.extend(
        [
            "| Check | Path | Line | Phrase | Detail |",
            "|---|---|---:|---|---|",
        ]
    )
    for finding in report.findings:
        lines.append(
            f"| {finding.check} | `{finding.path}` | {finding.line} | `{finding.phrase}` | {finding.detail} |"
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Guard RepoPilot UI copy against production-readiness and privacy overclaims.")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--json-out", type=Path)
    parser.add_argument("--md-out", type=Path)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.root.resolve()
    report = scan_targets(root)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(report.as_dict(), indent=2) + "\n", encoding="utf-8")
    if args.md_out:
        args.md_out.parent.mkdir(parents=True, exist_ok=True)
        args.md_out.write_text(render_markdown(report), encoding="utf-8")
    print(render_markdown(report))
    return 1 if report.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
